Testapp/Testapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_for_tests.urls', namespace='app_for_tests')),
]

Testapp/app_for_tests/urls.py
from django.urls import path
from . import views

app_name = 'app_for_tests'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.test_create, name='test_create'),  # Обновленный URL-адрес
    path('<int:test_id>/', views.choose_test, name='choose_test'),
    path('/<int:test_id>/start/', views.start_test, name='start_test'),  # Новый URL-шаблон для начала теста
    path('test_result/<int:test_id>/', views.test_result, name='test_result'),
    path('<int:test_id>/questions/<int:question_id>/', views.choose_question, name='choose_question'),
]

Testapp/app_for_tests/models.py
from django.db import models

class Test(models.Model):
    title = models.CharField(max_length=100, verbose_name='Test name')

    class Meta:
        verbose_name = 'Test'


class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    text = models.CharField(max_length=200, verbose_name='Question text')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Question'


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200, verbose_name='Answer text')
    is_correct = models.BooleanField(default=False, verbose_name='Is answer correct')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Answer'


class Result(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    user = models.CharField(max_length=200, verbose_name='User name')
    result = models.IntegerField(default=0, verbose_name='Result')

    def __str__(self):
        return f'{self.user}:{self.test}:{self.result}%'

    class Meta:
        verbose_name = 'Result'

Testapp/app_for_tests/forms.py
from django import forms
from .models import Test, Question, Answer

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['title']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'is_correct']


AnswerFormSet = forms.inlineformset_factory(
    Question,  # Родительская модель
    Answer,    # Дочерняя модель
    fields=['text', 'is_correct'],  # Поля, которые вы хотите отобразить в форме
    extra=4,   # Изначальное количество дополнительных форм
    can_delete=True,  # Позволяет удалять дополнительные формы
)

Testapp/app_for_tests/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Test, Question, Answer, Result
from .forms import TestForm, QuestionForm, AnswerForm


def index(request):
    test_list = Test.objects.all()
    template = 'app_for_tests/index.html'
    context = {'test_list': test_list,}

    return render(request, template, context)


def test_create(request):
    template = 'app_for_tests/test_create.html'
    context = {'test_form': test_form,}
    if request.method == 'POST':
        test_form = TestForm(request.POST)
        if test_form.is_valid():
            test = test_form.save()
            for key, value in request.POST.items():
                if key.startswith('question_text_'):
                    question_text = value
                    question = QuestionForm({'text': question_text})
                    if question.is_valid():
                        question = question.save(commit=False)
                        question.test = test
                        question.save()
                        question_index = key.split('_')[-1]
                        for i in range(4):
                            answer_text = request.POST.get(f'answer_text_{question_index}_{i}', '')
                            is_correct = request.POST.get(f'is_correct_{question_index}_{i}', False)
                            answer = AnswerForm({'text': answer_text, 'is_correct': is_correct})
                            if answer.is_valid():
                                answer = answer.save(commit=False)
                                answer.question = question
                                answer.save()
            return redirect('/')
    else:
        test_form = TestForm()
    return render(request, template, context)


def test_create(request):
    template = 'app_for_tests/test_create.html'

    if request.method == 'POST':
        test_form = TestForm(request.POST)
        if test_form.is_valid():
            test = test_form.save()
            for key, value in request.POST.items():
                if key.startswith('question_text_'):
                    question_text = value
                    question = QuestionForm({'text': question_text})
                    if question.is_valid():
                        question = question.save(commit=False)
                        question.test = test
                        question.save()
                        question_index = key.split('_')[-1]
                        for i in range(4):
                            answer_text = request.POST.get(f'answer_text_{question_index}_{i}', '')
                            is_correct = request.POST.get(f'is_correct_{question_index}_{i}', False)
                            answer = AnswerForm({'text': answer_text, 'is_correct': is_correct})
                            if answer.is_valid():
                                answer = answer.save(commit=False)
                                answer.question = question
                                answer.save()
            return redirect('/')  # Перенаправьте пользователя на страницу успешного создания
    else:
        test_form = TestForm()
    return render(request, template, {'test_form': test_form})


def choose_test(request, test_id):
    test = get_object_or_404(Test, pk=test_id)
    question_list = Question.objects.filter(test=test)
    template = 'app_for_tests/choose_test.html'
    context = {'test': test,
               'question_list': question_list,}
    return render(request, template, context)


def start_test(request, test_id):
    test = Test.objects.get(pk=test_id)
    questions = Question.objects.filter(test=test)
    template = 'app_for_tests/start_test.html'
    context = {'test': test, 'questions': questions}

    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        if user_name:
            # Получение ответов пользователя на вопросы
            user_answers = {}
            for question in questions:
                answer_id = request.POST.get(f'answer_{question.id}')
                if answer_id:
                    user_answers[question] = int(answer_id)

            # Вычисление результата теста
            score = 0
            for question, chosen_answer_id in user_answers.items():
                correct_answer_id = question.answer_set.filter(is_correct=True).first().id
                if chosen_answer_id == correct_answer_id:
                    score += 1
            result_percentage = round((score / len(questions)) * 100, 2)

            # Создание объекта результата и сохранение его в базе данных
            Result.objects.create(test=test, user=user_name, result=result_percentage)

            # Перенаправление пользователя на страницу с результатом теста
            return HttpResponseRedirect(
                reverse('app_for_tests:test_result', args=[test_id]) + f'?result={result_percentage}&user_name={user_name}')

    return render(request, template, context)


def choose_question(request, test_id, question_id):
    test = get_object_or_404(Test, pk=test_id)
    question = get_object_or_404(Question, pk=question_id)
    answer_list = Answer.objects.filter(question=question)
    template = 'app_for_tests/choose_question.html'
    context = {'test': test,
               'question': question,
               'answer_list': answer_list,}
    return render(request, template, context)


def test_result(request, test_id):
    test = get_object_or_404(Test, pk=test_id)
    question_list = Question.objects.filter(test=test)
    result = request.GET.get('result')  # Извлекаем результат из параметра запроса
    user_name = request.GET.get('user_name')

    template = 'app_for_tests/test_result.html'
    context = {'test': test,
               'question_list': question_list,
               'result': result,
               'user_name': user_name,}

    return render(request, template, context)

Testapp/templates/app_for_tests/choose_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1>choose_question</h1>
</head>
<body>

</body>
</html>

Testapp/templates/app_for_tests/choose_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1>Choose_test</h1>
    <h1>Тест: {{test.title}}</h1>
    <a href="{% url 'app_for_tests:start_test' test.id %}" class="btn btn-primary">Начать прохождение теста</a>

</head>
<body>

</body>
</html>

Testapp/templates/app_for_tests/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tests List</title>
</head>
<body>
    <h1>Available Tests</h1>
    <ul>
        {% for test in test_list %}
            <li><a href="{% url 'app_for_tests:choose_test' test.id %}">{{ test.title }}</a></li>
        {% endfor %}

    </ul>

    <a href="{% url 'app_for_tests:test_create' %}">Create Test</a>

</body>
</html>

Testapp/templates/app_for_tests/start_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start Test</title>
</head>
<body>
    {% if result %}
    <h1>Результат теста "{{ test.title }}"</h1>
    <p>Ваш результат: {{ result }}%</p>
    <!-- Другие детали о результатах теста, которые вы хотите отобразить -->
    {% else %}
    <h1>Прохождение теста "{{ test.title }}"</h1>
    <form method="post">
        {% csrf_token %}
        <label for="user_name">Введите ваше имя:</label>
        <input type="text" id="user_name" name="user_name" required>
        {% for question in questions %}
        <h3>{{ question.text }}</h3>
        {% for answer in question.answer_set.all %}
        <input type="radio" id="answer_{{ question.id }}_{{ answer.id }}" name="answer_{{ question.id }}" value="{{ answer.id }}">
        <label for="answer_{{ question.id }}_{{ answer.id }}">{{ answer.text }}</label><br>
        {% endfor %}
        {% endfor %}
        <button type="submit">Завершить тест</button>
    </form>
    {% endif %}
</body>
</html>

Testapp/templates/app_for_tests/test_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Test</title>
</head>
<body>
    <h1>Create Test</h1>
    <form method="post">
        {% csrf_token %}
        {{ test_form.as_p }}
        <label for="num_questions">Number of Questions:</label>
        <input type="number" id="num_questions" name="num_questions" min="1">
        <div id="questions-container"></div>
        <button type="button" onclick="addQuestions()">Add Questions</button>
        <input type="submit" value="Create Test">
    </form>

    <script>
        function addQuestions() {
            var numQuestions = document.getElementById('num_questions').value;
            var container = document.getElementById('questions-container');
            container.innerHTML = ''; // Очищаем контейнер перед добавлением новых вопросов
            for (var i = 0; i < numQuestions; i++) {
                var questionDiv = document.createElement('div');
                questionDiv.innerHTML = '<h3>Question ' + (i + 1) + '</h3>' +
                    '<input type="text" name="question_text_' + i + '" placeholder="Question text">' +
                    '<h4>Add Answers</h4>' +
                    '<input type="text" name="answer_text_' + i + '_0" placeholder="Answer text">' +
                    '<input type="checkbox" name="is_correct_' + i + '_0" id="is_correct_' + i + '_0">' +
                    '<label for="is_correct_' + i + '_0">Is correct</label>' +
                    '<input type="text" name="answer_text_' + i + '_1" placeholder="Answer text">' +
                    '<input type="checkbox" name="is_correct_' + i + '_1" id="is_correct_' + i + '_1">' +
                    '<label for="is_correct_' + i + '_1">Is correct</label>' +
                    '<input type="text" name="answer_text_' + i + '_2" placeholder="Answer text">' +
                    '<input type="checkbox" name="is_correct_' + i + '_2" id="is_correct_' + i + '_2">' +
                    '<label for="is_correct_' + i + '_2">Is correct</label>' +
                    '<input type="text" name="answer_text_' + i + '_3" placeholder="Answer text">' +
                    '<input type="checkbox" name="is_correct_' + i + '_3" id="is_correct_' + i + '_3">' +
                    '<label for="is_correct_' + i + '_3">Is correct</label>';
                container.appendChild(questionDiv);
            }
        }
    </script>
</body>
</html>

Testapp/templates/app_for_tests/test_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Result</title>
</head>
<body>
    <h1>Результат теста "{{ test.title }}"</h1>
    <p>{{user_name}}, ваш результат: {{ result }}%</p>
    <!-- Другие детали о результатах теста, которые вы хотите отобразить -->
</body>
</html>